/* The daily puzzle.
 *
 * One fixed position, the same for everybody, blue to move and red frozen.
 * "Destroy N pieces in M actions." Playable with nobody else online, which
 * is the whole point.
 *
 * Every puzzle is generated by the real rules engine and then *solved* by
 * it before being shipped, so an unsolvable daily can't happen. It is also
 * checked to be unsolvable one action faster, so the stated par is honest.
 */

import {
  SIZE, AP_PER_TURN,
  createGame, applyAction, legalActions, isHole, piecesOf,
  makeRandom, positionKey, ROLE
} from "./rules.js";

import { MAPS } from "./maps.js";

export const MAX_PUZZLE_ACTIONS = 4;

/** Build a rules state from a puzzle definition. */
export function puzzleState(def) {
  const state = createGame({ seed: def.id || 1, skipBans: true, mapId: def.mapId });
  state.board = Array.from({ length: SIZE }, () => Array(SIZE).fill(null));
  state.holes = def.holes.map(h => ({ r: h.r, c: h.c }));
  state.destroyed = { blue: 0, red: 0 };
  state.slamUsed = { blue: false, red: false };
  state.pieRule = { available: false, used: false };
  state.positions = {};
  state.current = "blue";
  state.ap = AP_PER_TURN;
  state.turn = 1;
  state.ring = 0;
  state.puzzle = true;

  for (const p of def.pieces) {
    state.board[p.r][p.c] = { id: p.id, color: p.color, role: p.role || ROLE.STANDARD };
  }
  return state;
}

/**
 * Apply an action inside a puzzle. Red never gets a turn, so once blue runs
 * out of action points the turn simply resets.
 */
export function puzzleApply(state, action) {
  const result = applyAction(state, action);
  if (!result.ok) return result;

  const next = result.state;
  if (next.phase === "playing" && next.current === "red") {
    next.current = "blue";
    next.ap = AP_PER_TURN;
    next.turn = 1; /* never let the board start closing mid-puzzle */
  }
  return { ...result, state: next };
}

/** Actions that make sense inside a puzzle. */
function puzzleActions(state) {
  return legalActions(state).filter(a => a.type !== "end" && a.type !== "swap");
}

/**
 * Depth-first search for a line that destroys `kills` red pieces within
 * `budget` actions. Returns the shortest such line, or null.
 */
export function solve(state, kills, budget) {
  let best = null;

  /* Transpositions are everywhere -- two steps in either order reach the
   * same board. Remember the deepest budget a position was already tried
   * with and skip anything that cannot do better. */
  const seen = new Map();

  const walk = (current, path) => {
    if (current.destroyed.red >= kills) {
      if (!best || path.length < best.length) best = path.slice();
      return;
    }
    if (path.length >= budget) return;
    if (best && path.length + 1 >= best.length) return;
    if (current.phase !== "playing") return;

    const remaining = budget - path.length;
    const key = positionKey(current) + "|" + current.destroyed.red;
    const bestSeen = seen.get(key);
    if (bestSeen !== undefined && bestSeen >= remaining) return;
    seen.set(key, remaining);

    for (const action of puzzleActions(current)) {
      const result = puzzleApply(current, action);
      if (!result.ok) continue;
      path.push(action);
      walk(result.state, path);
      path.pop();
    }
  };

  walk(state, []);
  return best;
}

/**
 * Cheap necessary condition: a red piece can only die if it has a hole on
 * one side and something can get behind it on the other. Boards that fail
 * this never reach the expensive search.
 */
function threatenableReds(state) {
  let count = 0;

  for (const red of piecesOf(state, "red")) {
    const pairs = [[-1, 0, 1, 0], [1, 0, -1, 0], [0, -1, 0, 1], [0, 1, 0, -1]];
    for (const [hr, hc, br, bc] of pairs) {
      const holeR = red.r + hr, holeC = red.c + hc;
      const backR = red.r + br, backC = red.c + bc;
      if (holeR < 0 || holeR >= SIZE || holeC < 0 || holeC >= SIZE) continue;
      if (backR < 0 || backR >= SIZE || backC < 0 || backC >= SIZE) continue;
      if (!isHole(state, holeR, holeC)) continue;
      if (isHole(state, backR, backC)) continue;

      const behind = state.board[backR][backC];
      if (!behind || behind.color === "blue") { count++; break; }
    }
  }

  return count;
}

/* ------------------------------------------------------------- generation */

function emptySquares(state) {
  const out = [];
  for (let r = 0; r < SIZE; r++) {
    for (let c = 0; c < SIZE; c++) {
      if (!isHole(state, r, c) && !state.board[r][c]) out.push({ r, c });
    }
  }
  return out;
}

function draw(list, random) {
  return list[Math.floor(random() * list.length)];
}

/**
 * Build the puzzle for a given day number. Deterministic: the same day
 * always produces the same board, on the server and in the browser.
 */
export function generateDaily(day, attempts = 400) {
  const random = makeRandom((day + 1) * 2654435761);

  for (let attempt = 0; attempt < attempts; attempt++) {
    const map = MAPS[Math.floor(random() * MAPS.length)];
    const kills = random() < 0.35 ? 3 : 2;
    const budget = kills === 3 ? 4 : 3;

    const def = {
      id: day,
      mapId: map.id,
      holes: map.holes.map(([r, c]) => ({ r, c })),
      pieces: [],
      goal: { kills, actions: budget }
    };

    const scratch = puzzleState(def);
    const free = emptySquares(scratch);
    if (free.length < 10) continue;

    const taken = new Set();
    const place = (color, n) => {
      for (let i = 0; i < n; i++) {
        let spot = null;
        for (let tries = 0; tries < 40 && !spot; tries++) {
          const candidate = draw(free, random);
          const key = candidate.r + "," + candidate.c;
          if (!taken.has(key)) { spot = candidate; taken.add(key); }
        }
        if (!spot) return false;
        def.pieces.push({
          r: spot.r, c: spot.c, color,
          role: ROLE.STANDARD,
          id: color[0] + (def.pieces.length + 1)
        });
      }
      return true;
    };

    if (!place("blue", 3)) continue;
    if (!place("red", kills + 1)) continue;

    const state = puzzleState(def);

    /* Skip the expensive search on boards where nothing can even be
     * threatened. This throws out most candidates almost for free. */
    if (threatenableReds(state) < 1) continue;

    /* Must be solvable at par... */
    const line = solve(state, kills, budget);
    if (!line || line.length !== budget) continue;

    /* ...and not one action sooner, or the stated par is a lie. */
    if (solve(state, kills, budget - 1)) continue;

    def.solutionLength = line.length;
    return def;
  }

  /* Fall back to a hand-built position rather than shipping nothing. */
  return fallbackPuzzle(day);
}

function fallbackPuzzle(day) {
  const def = {
    id: day,
    mapId: "crossroads",
    holes: [[2, 1], [2, 5], [3, 3], [4, 1], [4, 5]].map(([r, c]) => ({ r, c })),
    pieces: [
      { r: 3, c: 1, color: "blue", role: ROLE.STANDARD, id: "b1" },
      { r: 3, c: 2, color: "red",  role: ROLE.STANDARD, id: "r1" },
      { r: 2, c: 3, color: "blue", role: ROLE.STANDARD, id: "b2" },
      { r: 1, c: 3, color: "red",  role: ROLE.STANDARD, id: "r2" },
      { r: 5, c: 5, color: "red",  role: ROLE.STANDARD, id: "r3" }
    ],
    goal: { kills: 2, actions: 2 }
  };
  def.fallback = true;
  return def;
}

/**
 * Replay a submitted line against the real rules. The client is never
 * trusted to say it solved anything.
 */
export function verifySolution(def, actions) {
  if (!Array.isArray(actions)) return { solved: false, reason: "No moves sent." };
  if (actions.length > def.goal.actions) {
    return { solved: false, reason: "That is more moves than the puzzle allows." };
  }

  let state = puzzleState(def);

  for (const action of actions) {
    const result = puzzleApply(state, action);
    if (!result.ok) return { solved: false, reason: result.reason };
    state = result.state;
  }

  if (state.destroyed.red >= def.goal.kills) {
    return { solved: true, used: actions.length };
  }
  return {
    solved: false,
    reason: "Only " + state.destroyed.red + " of " + def.goal.kills + " destroyed."
  };
}
